name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # This will use your local runner

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nodejs-app:${{ github.run_number }}

      - name: Deploy to Kubernetes
        env:
          KUBE_CONFIG_BASE64: ${{ secrets.KUBE_CONFIG }}
        run: |
          # Decode the base64 encoded kubeconfig and save it
          echo "$KUBE_CONFIG_BASE64" | base64 -d > kubeconfig
          export KUBECONFIG=kubeconfig

          # Update the image tag in deployment.yml
          sed -i 's|image: nodejs-app:.*|image: nodejs-app:${{ github.run_number }}|' k8s/deployment.yml

          # Apply Kubernetes manifests
          kubectl apply -f k8s/deployment.yml
          kubectl apply -f k8s/service.yml
          kubectl apply -f k8s/ingress.yml

          # Ensure the deployment is rolled out
          kubectl rollout status deployment/your-deployment-name

          # Clean up the kubeconfig file
          rm kubeconfig
